image:
  name: atlassian/default-image:3

test: &test
  step:
    name: Test
    script:
      - npm install -g bats
      - chmod a+x test/*.bats
      - bats test/test.bats
    services:
      - docker

pipelines:
  default:
    - <<: *test
